title: "EDM Portfolio"
description: "Enterprise Data Management Portfolio"
author: Sanidad, Justine Reinn V.
<img src="/pfp/pfp.jpg" alt="My Logo" width="150">

show_downloads: true

github:
  is_project_page: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

